version: "2.3"
services:
  queue:
    image: ibl/dlc:base
    command: python3 -c "from iblvideo import run_queue; run_queue()"
    runtime: nvidia
    volumes:
      - /mnt/s0/Data/FlatIron:/mnt/s0/Data/FlatIron
      - ~/Documents/PYTHON/00_IBL/iblvideo:/root
  test:
    image: ibl/dlc:base
    command: pytest /root/iblvideo/tests
    runtime: nvidia
    volumes:
      - ~/Documents/PYTHON/00_IBL/iblvideo:/root
      - /mnt/s0/Data/FlatIron:/mnt/s0/Data/FlatIron
