#docker build -t internationalbrainlab/dlc:v2.0 -f Dockerfile.v2.0 --no-cache .
FROM internationalbrainlab/dlc:base

# copy the weights and test data
COPY weights_v2.0 weights_v2.0
COPY me_test_data me_test_data
COPY dlc_test_data_v2.0 dlc_test_data_v2.0

# clone the code
RUN git clone --depth 1 --single-branch --branch one2 https://github.com/int-brain-lab/iblvideo.git
ENV PYTHONPATH=/iblvideo
